import { useEffect,useRef,useState } from 'react';
import { useNavigate,useParams,useSearchParams } from 'react-router-dom';
import { AlertTriangle,Building2,LogIn,Package,ShieldCheck,Wrench } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import BrandLogo from '../components/BrandLogo';

export default function AssetQrPage(){
  const {token}=useParams(); const navigate=useNavigate(); const [params]=useSearchParams(); const {profile,loading:authLoading}=useAuth();
  const [asset,setAsset]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [opening,setOpening]=useState(false); const redirected=useRef(false);
  useEffect(()=>{(async()=>{const {data,error:e}=await supabase.rpc('get_public_asset_by_qr',{p_token:token});if(e||!data)setError('QR Code tidak valid atau data aset tidak ditemukan.');else setAsset(data);setLoading(false)})()},[token]);
  const openService=async()=>{if(!profile){navigate(`/login?returnTo=${encodeURIComponent(`/scan/assets/${token}?service=1`)}`);return}setOpening(true);const {data,error:e}=await supabase.rpc('resolve_asset_qr',{p_token:token});if(e||!data){setError('Aset tidak dapat dibuka. Pastikan akun Anda aktif.');setOpening(false);return}navigate(`/assets/${data}?service=1`)};
  useEffect(()=>{if(!authLoading&&profile&&asset&&params.get('service')==='1'&&!redirected.current){redirected.current=true;openService()}},[authLoading,profile,asset]);
  if(loading||authLoading)return <div className="min-h-screen bg-ink-950 flex items-center justify-center text-ink-300">Memuat informasi aset...</div>;
  if(error||!asset)return <div className="min-h-screen bg-ink-950 flex items-center justify-center p-5"><div className="card max-w-md text-center"><AlertTriangle className="mx-auto text-warning-400 mb-4" size={42}/><h1 className="text-xl font-semibold text-white">Aset tidak ditemukan</h1><p className="text-sm text-ink-400 mt-2">{error}</p></div></div>;
  const fields=[['Kode Aset',asset.asset_code],['Nama Aset',asset.asset_name],['Merek',asset.brand],['Tipe / Model',asset.model],['Kategori',asset.category_name],['Lokasi',asset.location_name],['Penanggung Jawab',asset.responsible_name],['Kondisi',asset.condition_name],['Status',asset.status_name||(asset.is_active?'Aktif':'Nonaktif')]];
  return <div className="min-h-screen bg-ink-950 text-white relative overflow-hidden"><div className="absolute inset-0 dot-grid-bg opacity-30 pointer-events-none"/><header className="relative border-b border-white/10 bg-ink-950/85 backdrop-blur-xl"><div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between gap-4"><BrandLogo className="w-36 h-12 sm:w-44 sm:h-14"/><span className="text-[10px] sm:text-[11px] uppercase tracking-[.14em] sm:tracking-[.18em] text-ink-500 text-right">Informasi Aset</span></div></header><main className="relative max-w-3xl mx-auto px-4 py-5 md:py-10">
    <section className="card overflow-hidden !p-0"><div className="grid md:grid-cols-[220px_1fr]"><div className="bg-white/[.03] min-h-52 flex items-center justify-center p-4 border-b md:border-b-0 md:border-r border-white/10">{asset.photo_url?<img src={asset.photo_url} alt={asset.asset_name} className="w-full h-52 object-contain rounded-xl bg-black/20"/>:<Package size={58} className="text-ink-700"/>}</div><div className="p-5 md:p-7"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-primary-400 text-sm">{asset.asset_code}</p><h1 className="text-2xl md:text-3xl font-semibold mt-1">{asset.asset_name}</h1></div><span className={asset.repair_in_progress?'badge-yellow':'badge-green'}>{asset.repair_in_progress?'Dalam Perbaikan':'Operasional'}</span></div><p className="text-sm text-ink-400 mt-3">Informasi terverifikasi dari sistem manajemen aset Harmas.</p></div></div></section>
    {asset.repair_in_progress&&<section className="mt-4 rounded-2xl border border-warning-500/25 bg-warning-500/10 p-5"><div className="flex gap-3"><Wrench className="text-warning-400 flex-shrink-0" size={20}/><div><p className="font-semibold text-warning-200">{asset.repair_status==='OPEN'?'Menunggu penanganan':'Sedang diperbaiki'}</p><p className="text-sm text-ink-300 mt-1">{asset.repair_description}</p>{asset.repair_date&&<p className="text-xs text-ink-500 mt-2">Dicatat {new Date(asset.repair_date).toLocaleDateString('id-ID')}</p>}</div></div></section>}
    <section className="card mt-4"><div className="flex items-center gap-2 mb-4"><Building2 size={17} className="text-primary-400"/><h2 className="font-semibold">Detail Mesin / Aset</h2></div><div className="grid sm:grid-cols-2 gap-3">{fields.map(([label,value])=><div key={label} className="rounded-xl border border-white/8 bg-white/[.025] p-3.5"><p className="text-[10px] uppercase tracking-wider text-ink-500">{label}</p><p className="text-sm text-ink-100 mt-1 font-medium">{value||'-'}</p></div>)}</div></section>
    <section className="card mt-4"><div className="flex items-start gap-3"><ShieldCheck className="text-success-400 flex-shrink-0" size={20}/><div className="flex-1"><h2 className="font-semibold">Menemukan kerusakan?</h2><p className="text-sm text-ink-400 mt-1">Login diperlukan untuk mencatat service dan mengunggah foto part yang rusak.</p><button onClick={openService} disabled={opening} className="btn-primary mt-4 w-full sm:w-auto">{profile?<Wrench size={15}/>:<LogIn size={15}/>} {opening?'Membuka...':'Catat Service'}</button></div></div></section>
  </main></div>;
}
